version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Group all codeql actions into 1 PP
    # For instacen `init` and `analyze` depend on each other and must
    # be updated simultaneously
    groups:
      codeql-action:
        patterns:
          - "github/codeql-action/*"
