name: PR Checks

on:
  pull_request:
    branches:
      - 'master'

env:
  # Golang version to use across CI steps
  GOLANG_VERSION: '1.22'
  SBOM_PATH: sbom.json

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-go:
    name: Build Go
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4.0.0

      - name: Setup Golang
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: ${{ env.GOLANG_VERSION }}

      - name: Download all Go modules
        run: |
          go mod download

      - name: Build
        run: |
          go build
          # Since tests are outside the scope, lets just try a quick run
          ./calculator-cli -h

  lint-go:
    name: Go lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4.0.0

      - name: golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
